### ISSUE TITLE
Updating Skript from v2.5.3 to v2.6-beta3 somehow broke loop-list

### ISSUE THREAD

**Issue by oskarkk** [Sashie/skript-yaml#37] opened 2021-10-09 02:06 UTC
test.sk:

```
on script load:
  load yml "plugins/Skript/scripts/test.yml" as "test"

command /test:
  trigger:
    loop yaml node list "abc" from "test":
      log "%loop-list%"
```

test.yml:

```
abc:
  foo:
   - 1
   - 2
  bar:
   - 3
   - 4
```

Result on Skript v2.5.3:

```
> test
[03:59:05 Server thread/INFO] [Skript] [test.sk] 1 and 2
[03:59:05 Server thread/INFO] [Skript] [test.sk] 3 and 4
```

Result on v2.6-beta3:

```
> test
[03:57:58 Server thread/INFO] [Skript] [test.sk] abc.foo
[03:57:58 Server thread/INFO] [Skript] [test.sk] abc.bar
```

The bug is the same on skript-yaml v1.4 and v1.3.2

**Comment by wallace4BR** [comment] 2021-10-09 02:16
currently caused by some changes on skript 2.6, in the next skript-yaml version this bug will be fixed

**Comment by oskarkk** [comment] 2021-10-09 02:28
Okay, thanks. Just found that loop-key also gives the whole node path.

**Closed** 2023-02-04 03:40 UTC
