### ISSUE TITLE
error loading the yml file

### ISSUE THREAD

**Issue by dver63** [Sashie/skript-yaml#57] opened 2024-07-17 16:55 UTC
i was trying to upload a .yml file via skript, but this error appeared when I used the /rr command:

[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! [Skript] Severe Error:
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Something went horribly wrong with Skript.
[20:40:28 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:40:28 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:40:28 ERROR]: #!#! Here is full list of them:
[20:40:28 ERROR]: #!#! skript-yaml v1.5 
[20:40:28 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:40:28 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:40:28 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:40:28 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:40:28 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:40:28 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Stack trace:
[20:40:28 ERROR]: #!#! java.lang.IllegalStateException: zip file closed
[20:40:28 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[20:40:28 ERROR]: #!#!     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[20:40:28 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[20:40:28 ERROR]: #!#!     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[20:40:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[20:40:28 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[20:40:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[20:40:28 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[20:40:28 ERROR]: #!#!     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//net.kyori.adventure.text.serializer.bungeecord.SelfSerializable$AdapterFactory.create(SelfSerializable.java:58)
[20:40:28 ERROR]: #!#!     at com.google.gson.Gson.getAdapter(Gson.java:556)
[20:40:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:834)
[20:40:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:812)
[20:40:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:759)
[20:40:28 ERROR]: #!#!     at com.google.gson.Gson.toJson(Gson.java:736)
[20:40:28 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:175)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//net.kyori.adventure.text.serializer.bungeecord.BungeeComponentSerializer.deserialize(BungeeComponentSerializer.java:142)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:107)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.expressions.ExprChestInventory.get(ExprChestInventory.java:46)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:97)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:60)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:106)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:345)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.command.ScriptCommand.lambda$execute$0(ScriptCommand.java:304)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:315)
[20:40:28 ERROR]: #!#!     at Skript-2.9.0.jar//ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:250)
[20:40:28 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:40:28 ERROR]: #!#!     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[20:40:28 ERROR]: #!#!     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:353)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:340)
[20:40:28 ERROR]: #!#!     at net.minecraft.commands.Commands.performCommand(Commands.java:335)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:40:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:40:28 ERROR]: #!#!     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:40:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449)
[20:40:28 ERROR]: #!#!     at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246)
[20:40:28 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[20:40:28 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Version Information:
[20:40:28 ERROR]: #!#!   Skript: 2.9.0 (latest)
[20:40:28 ERROR]: #!#!     Flavor: skriptlang-github
[20:40:28 ERROR]: #!#!     Date: 16:01:35.354421100
[20:40:28 ERROR]: #!#!   Bukkit: 1.21-R0.1-SNAPSHOT
[20:40:28 ERROR]: #!#!   Minecraft: 1.21
[20:40:28 ERROR]: #!#!   Java: 22.0.2 (Java HotSpot(TM) 64-Bit Server VM 22.0.2+9-70)
[20:40:28 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Server platform: Paper
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Current node: null
[20:40:28 ERROR]: #!#! Current item: open chest inventory named "Правила регионов" with [[long:3]] to the player
[20:40:28 ERROR]: #!#! Current trigger: command /regionrules (simple event) (rr\rr.sk, line 8)
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Thread: Server thread
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! Language: english
[20:40:28 ERROR]: #!#! Link parse mode: DISABLED
[20:40:28 ERROR]: #!#! 
[20:40:28 ERROR]: #!#! End of Error.
[20:40:28 ERROR]: #!#! 

rr.sk:
```skript
command /regionrules:
	usage: /regionrules или /rr
	description: Вызывает графический интерфейс RegionRules
	permission: regionrules.command.regionrules
	permission message: У вас недостаточно прав!
	aliases: /rr
	executable by: players
	trigger:
		if player has permission "regionrules.storage.edit":
			open chest inventory with 3 rows named "Правила регионов" to player
			set {_items::*} to yaml list "regionrules.storage.items" from "plugins/Skript/scripts/rr/storage.yml"
			loop {_items::*}:
				set {_index} to loop-index
				set {_value} to loop-value
				set slot {_index} of player's current inventory to {_value}
		else if player has permission "regionrules.storage.view":
			open chest inventory with 3 rows named "Правила регионов" to player
			set {_items::*} to yaml list "regionrules.storage.items" from "plugins/Skript/scripts/rr/storage.yml"
			loop {_items::*}:
				set {_index} to loop-index
				set {_value} to loop-value
				if {_value} is book:
					set slot {_index} of player's current inventory to {_value}
		else:
			send "У вас нет прав для использования этого сундука." to player

on inventory close:
	if name of player's current inventory is "Правила регионов":
		if player has permission "regionrules.storage.edit":
			set {_items::*} to all items in player's current inventory
			set yaml list "regionrules.storage.items" from "plugins/Skript/scripts/rr/storage.yml" to {_items::*}
```

if you disable the script-yaml plugin, then my code just stops working.

**Comment by Sashie** [comment] 2024-10-26 02:43
The error you shared shows what appears to be the cause. Closing this issue as it is not related to skript-yaml

[20:40:28 ERROR] #!#! Current item: open chest inventory named "Правила регионов" with [[long:3]] to the player

**Closed by Sashie** 2024-10-26 02:43 UTC
